# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d4c0c3df169faf6e3be35fce4c2ef5968e3bf8030a494aec99065ca6909a3a3cd7fbd7d5f1a9084045eb2d3675e18becddb673787918f4c0217fa552674c6a4

test:
  secret_key_base: b19a53c96f938b90cc04c0a755b41737c6778fe3078b48291c92146f2ee48e69b6bdd3e6e2f848d6e7fe09a1e4452bd94d8f1f34c4250fa8d2e1f29835d7b266

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
